### ISSUE TITLE
Tutorial #1 - Build an audio player

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/drc#2]
# 개요
https://docs.juce.com/master/tutorial_playing_sound_files.html
### 튜토리얼 목적
본 튜토리얼은 JUCE Framework를 사용한 첫 프로젝트이며, JUCE Framework를 익히고 JUCE를 활용한 오디오 프로그램 개발의 플로우를 이해하는 데에 있다.

### 설명
Sound File (.wav .aiff)을 열고 음악을 재생한다.

# TODO List
- [x] 새로운 JUCE 프로젝트 만들기
- [x] Open / Start / Stop 버튼 UI 추가
- [x] Open / Start / Stop 버튼 로직 구현
- [x] AudioFormatManager를 통해 .wav 음원 파일 읽기
- [x] AudioSource (AudioReaderSource / AudioTransportSource)를 통해 음원 재생하기

**Comment by ollybaysion** [comment]
#### TextButton
TextButton에 대해서 알아본다.
아래에 설명되어 있지 않은 더욱 자세한 설명은 다음 JUCE 공식 문서를 참고한다.
https://docs.juce.com/master/classTextButton.html

##### 선언
```cpp
juce:TextButton openButton;
```

##### Main Component에 추가
```
addAndMakeVisible(&openButton);
```

##### 버튼 이름
```
 openButton.setButtonText("Open...");
```

##### 색 변경
```
openButton.setColour(juce::TextButton::buttonColourId, juce::Colours::green);
```

##### 활성화/비활성화
```
openButton.setEnabled(false);
```

**Comment by ollybaysion** [comment]
## Open 버튼
### File Chooser
파일 선택

### AudioFormatManager
Reader

### AudioFormatReaderSource
Audio Source

### **AudioTransportSource
음악 재생 / 정지와 관련된 기능 제공

**Comment by ollybaysion** [comment]
## 다음 Task 정리
- AudioSource 
- AudioBuffer
- .wav 파일 저장을 위한 방법 (Writer 관련 예상)

**Comment by ollybaysion** [comment]
시연을 마쳤으므로 이슈를 종료합니다
